# Generated by Django 2.2.7 on 2020-03-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20200226_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shop_image',
            field=models.ImageField(default=1, upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='shop_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
