# Generated by Django 2.2.7 on 2020-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20200319_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paint_title', models.CharField(max_length=200)),
                ('paint_text', models.TextField()),
                ('paint_image', models.ImageField(upload_to='gallery/')),
            ],
        ),
    ]
