# Generated by Django 2.2.7 on 2020-03-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_paint'),
    ]

    operations = [
        migrations.AddField(
            model_name='paint',
            name='paint_title_rus',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paint',
            name='paint_text',
            field=models.CharField(max_length=200),
        ),
    ]
